### ISSUE TITLE
Add a customization option for colors for wave bar and duration text

### ISSUE THREAD

**Issue by Muneeb1294** [csells/waveform_recorder#2]
Should add a customization option for colors for the wave bar and also the duration text.

**Comment by csells** [comment]
waiting on https://github.com/agenthesh/waveform/pull/6 to be merged

**Comment by Muneeb1294** [comment]
> waiting on [agenthesh/waveform#6](https://github.com/agenthesh/waveform/pull/6) to be merged

Any idea how much time it can take?

**Comment by csells** [comment]
> Any idea how much time it can take?

My [last PR with @agenthesh on his waveform project](https://github.com/agenthesh/waveform/pull/3) was a 2-day turn-around.

**Comment by csells** [comment]
updated `waveform_recorder` to add `waveColor` and `durationTextStyle` parameters to the `WaveformRecorder` constructor.
